// Generated by scripts/export_word_contract.py. Do not edit.
// Validate wire values with the JSON Schemas AND semantic fixture suite.

export type identifier = string;

export type englishWord = string;

export type score = number;

export type producer = {
  readonly "recognizer_id": "signchat_asl_signs_onnx";
  readonly "recognizer_version": "signchat_asl_signs_onnx";
  readonly "translator_id": "asl_label_to_english";
  readonly "translator_version": "1.0.0";
  readonly "vocabulary_version": "popsign_250_en_v1";
  readonly "confidence_kind": "normalized_model_score";
};

export type alternative = {
  readonly "rank": number;
  readonly "word": englishWord;
  readonly "confidence": score;
};

export type wordToken = {
  readonly "index": number;
  readonly "token_id": identifier;
  readonly "word": englishWord;
  readonly "confidence": score;
  readonly "alternatives": ReadonlyArray<alternative>;
};

export type AcceptedMessage = {
  readonly "message_id": string;
  readonly "sender_id": string;
  readonly "client_sequence": number;
  readonly "server_sequence": number;
  readonly "context_version": number;
  readonly "source": "sign" | "text" | "speech";
  readonly "status"?: "accepted";
  readonly "text": string;
  readonly "translation"?: AcceptedOutcome | null;
};

export type AcceptedOutcome = {
  readonly "status"?: "accepted";
  readonly "text": string;
  readonly "tts_text"?: string | null;
  readonly "confidence": number;
  readonly "confidence_kind"?: "normalized_model_score";
  readonly "model_version": string;
  readonly "policy_version": string;
};

export type ActivityEvent = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "activity";
  readonly "participant_id": string;
  readonly "state": "idle" | "typing" | "listening" | "signing";
};

export type MessageUpsert = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "message_upsert";
  readonly "message": ProcessingMessage | AcceptedMessage | RepairMessage;
};

export type ParticipantView = {
  readonly "participant_id": string;
  readonly "role": "signer" | "hearing";
  readonly "alias": string;
  readonly "online": boolean;
};

export type Pong = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "pong";
};

export type PresenceEvent = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "presence";
  readonly "participant": ParticipantView;
};

export type ProcessingMessage = {
  readonly "message_id": string;
  readonly "sender_id": string;
  readonly "client_sequence": number;
  readonly "server_sequence": number;
  readonly "context_version": number;
  readonly "source"?: "sign";
  readonly "status"?: "processing";
};

export type RepairMessage = {
  readonly "message_id": string;
  readonly "sender_id": string;
  readonly "client_sequence": number;
  readonly "server_sequence": number;
  readonly "context_version": number;
  readonly "source"?: "sign";
  readonly "status"?: "repair";
  readonly "repair": RepairOutcome;
};

export type RepairOutcome = {
  readonly "status"?: "repair";
  readonly "action": "ask_repeat" | "offer_alternatives" | "request_fingerspelling" | "ask_type" | "escalate_human_interpreter";
  readonly "prompt": string;
  readonly "reason_code": "policy_unconfigured" | "unsupported_vocabulary" | "low_score" | "ambiguous_words" | "unresolved_content" | "unsupported_detail" | "invalid_alignment" | "unnatural_sentence" | "context_conflict" | "invalid_output" | "provider_failure" | "timeout" | "cancelled" | "capacity" | "revision_exhausted";
  readonly "target_indices"?: ReadonlyArray<number>;
};

export type RoomEnded = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "room_ended";
};

export type RoomError = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "error";
  readonly "code": "resync_required" | "invalid_control" | "rate_limited";
};

export type RoomSnapshot = {
  readonly "event_schema_version"?: "1.0";
  readonly "room_version": number;
  readonly "type"?: "snapshot";
  readonly "code": string;
  readonly "state": "waiting" | "active";
  readonly "context_version": number;
  readonly "participants": ReadonlyArray<ParticipantView>;
  readonly "messages": ReadonlyArray<ProcessingMessage | AcceptedMessage | RepairMessage>;
};

export type Activity = {
  readonly "type": "activity";
  readonly "state": "idle" | "typing" | "listening" | "signing";
};

export type EndRoom = {
  readonly "type": "end";
};

export type Ping = {
  readonly "type": "ping";
};

export type TranslatedSignUtteranceV1 = {
  readonly "type": "translated_sign_utterance";
  readonly "schema_version": "1.0";
  readonly "message_id": string;
  readonly "client_sequence": number;
  readonly "source_language": "asl";
  readonly "target_language": "en";
  readonly "is_final": true;
  readonly "completion_reason": "user_commit";
  readonly "producer": producer;
  readonly "words": ReadonlyArray<wordToken>;
};

export type RoomEvent = RoomSnapshot | MessageUpsert | PresenceEvent | ActivityEvent | RoomEnded | RoomError | Pong;

export type SocketInput = Activity | EndRoom | Ping;

export type RoomCredentials = {
  readonly "event_schema_version"?: "1.0";
  readonly "utterance_schema_version"?: "1.0";
  readonly "code": string;
  readonly "participant_id": string;
  readonly "role": "signer" | "hearing";
  readonly "token": string;
  readonly "join_path": string;
};

export type UtteranceAck = {
  readonly "event_schema_version"?: "1.0";
  readonly "type"?: "utterance_ack";
  readonly "message_id": string;
  readonly "client_sequence": number;
  readonly "server_sequence": number;
  readonly "disposition": "accepted" | "cached";
};

export type CreateRoom = {
  readonly "schema_version": "1.0";
  readonly "event_schema_version": "1.0";
  readonly "alias": string;
};

export type JoinRoom = {
  readonly "schema_version": "1.0";
  readonly "event_schema_version": "1.0";
  readonly "alias": string;
  readonly "code": string;
};

export type TextMessage = {
  readonly "schema_version": "1.0";
  readonly "message_id": string;
  readonly "client_sequence": number;
  readonly "source": "text" | "speech";
  readonly "text": string;
};

export type Authenticate = {
  readonly "type": "authenticate";
  readonly "event_schema_version": "1.0";
  readonly "token": string;
};
