"""Reproducible v1 handoff generated from packaged schemas, never client field lists."""

from __future__ import annotations

import argparse
import json
from importlib.resources import files
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from simplynext.contracts.room_events import ROOM_EVENT_ADAPTER, RoomCredentials, UtteranceAck
from simplynext.contracts.room_inputs import (
    Authenticate,
    CreateRoom,
    JoinRoom,
    SocketInput,
    TextMessage,
)

ROOT = Path(__file__).resolve().parents[1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(ts_type(item) for item in schema[key])
    kind = str(schema.get("type", ""))
    if kind == "array":
        return f"ReadonlyArray<{ts_type(schema['items'])}>"
    if kind == "object":
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  readonly {json.dumps(key)}{'' if key in required else '?'}: {ts_type(value)};"
                for key, value in schema.get("properties", {}).items()
            )
            + "\n}"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def artifacts() -> dict[Path, str]:
    schema = json.loads(
        files("simplynext")
        .joinpath(
            "contracts/schemas/translated-sign-utterance-v1.json",
        )
        .read_text()
    )
    events = ROOM_EVENT_ADAPTER.json_schema()
    events["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    events["$id"] = "https://signbridge.example/schemas/room-events-v1.json"
    docs = {"TranslatedSignUtteranceV1": schema, "RoomEvent": events}
    docs["SocketInput"] = TypeAdapter(SocketInput).json_schema()
    for model in (RoomCredentials, UtteranceAck, CreateRoom, JoinRoom, TextMessage, Authenticate):
        docs[model.__name__] = model.model_json_schema()
    definitions: dict[str, Any] = {}
    for document in docs.values():
        for name, value in document.get("$defs", {}).items():
            if name in definitions and definitions[name] != value:
                raise ValueError(f"conflicting schema definition: {name}")
            definitions[name] = value
    definitions.update(docs)
    types = "// Generated by scripts/export_word_contract.py. Do not edit.\n"
    types += "// Validate wire values with the JSON Schemas AND semantic fixture suite.\n\n"
    types += (
        "\n\n".join(
            f"export type {name} = {ts_type(value)};" for name, value in definitions.items()
        )
        + "\n"
    )
    return {
        ROOT / "client/room-v1.ts": types,
        ROOT / "src/simplynext/contracts/schemas/room-events-v1.json": json.dumps(events, indent=2)
        + "\n",
        ROOT / "client/room-http-v1.schema.json": json.dumps(
            {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "$defs": definitions,
            },
            indent=2,
        )
        + "\n",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, text in artifacts().items():
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f"stale generated artifact: {path.relative_to(ROOT)}")
        else:
            path.write_text(text)


if __name__ == "__main__":
    main()
